# Generated by Django 4.1.7 on 2023-04-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalarySlip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Employee_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
