# Generated by Django 4.1.7 on 2023-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalarySlip', '0002_alter_teacher_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='excel',
            field=models.FileField(upload_to='media/AllMonthData'),
        ),
    ]
