# Generated by Django 4.1.7 on 2023-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalarySlip', '0003_alter_report_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Images'),
        ),
    ]
