# Generated by Django 5.0.1 on 2024-04-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalarySlip', '0004_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Degisnation',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
